package Census::US::Decennial2000SF2Iterations;
1;
__END__
"Iteration Code","Iterations"
"001","Total population"
"002","   White alone"
"003","   White alone or in combination with one or more other races"
"004","   Black or African American alone"
"005","   Black or African American alone or in combination with one or more other races"
"006","   American Indian and Alaska Native alone"
"007","     American Indian alone"
"008","     Alaska Native alone"
"009","   American Indian and Alaska Native alone or in combination with one or more other races"
"010","     American Indian alone or in any combination"
"011","     Alaska Native alone or in any combination"
"012","   Asian alone"
"013","     Asian Indian alone"
"014","     Bangladeshi alone"
"015","     Cambodian alone"
"016","     Chinese alone"
"017","        Chinese, except Taiwanese, alone"
"018","        Taiwanese alone"
"019","     Filipino alone"
"020","     Hmong alone"
"021","     Indonesian alone"
"022","     Japanese alone"
"023","     Korean alone"
"024","     Laotian alone"
"025","     Malaysian alone"
"026","     Pakistani alone"
"027","     Sri Lankan alone"
"028","     Thai alone"
"029","     Vietnamese alone"
"030","     Other specified Asian alone"
"031","   Asian alone or in combination with one or more other races"
"032","     Asian Indian alone or in any combination"
"033","     Bangladeshi alone or in any combination"
"034","     Cambodian alone or in any combination"
"035","     Chinese alone or in any combination"
"036","        Chinese, except Taiwanese, alone or in any combination"
"037","        Taiwanese alone or in any combination"
"038","     Filipino alone or in any combination"
"039","     Hmong alone or in any combination"
"040","     Indonesian alone or in any combination"
"041","     Japanese alone or in any combination"
"042","     Korean alone or in any combination"
"043","     Laotian alone or in any combination"
"044","     Malaysian alone or in any combination"
"045","     Pakistani alone or in any combination"
"046","     Sri Lankan alone or in any combination"
"047","     Thai alone or in any combination"
"048","     Vietnamese alone or in any combination"
"049","     Other specified Asian alone or in any combination"
"050","   Native Hawaiian and Other Pacific Islander alone"
"051","     Polynesian alone"
"052","        Native Hawaiian alone"
"053","        Samoan alone"
"054","        Tongan alone"
"055","     Micronesian alone"
"056","        Guamanian or Chamorro alone"
"057","     Melanesian alone"
"058","        Fijian alone"
"059","     Other specified Pacific Islander alone"
"060","   Native Hawaiian and Other Pacific Islander alone or in combination with one or more other races"
"061","     Polynesian alone or in any combination"
"062","        Native Hawaiian alone or in any combination"
"063","        Samoan alone or in any combination"
"064","        Tongan alone or in any combination"
"065","     Micronesian alone or in any combination"
"066","        Guamanian or Chamorro alone or in any combination"
"067","     Melanesian alone or in any combination"
"068","        Fijian alone or in any combination"
"069","     Other specified Pacific Islander alone or in any combination"
"070","   Some other race alone"
"071","   Some other race alone or in combination with one or more other races"
"100","   Two or more races"
"101","     Two races including Some other race"
"102","     Two races excluding Some other race, and three or more races"
"103","        Two races excluding Some other race"
"104","        Three or more races"
"105","     White; Black or African American"
"106","     White; American Indian and Alaska Native"
"107","     White; Asian"
"108","     White; Native Hawaiian and Other Pacific Islander"
"109","     White; Some other race"
"110","     Black or African American; American Indian and Alaska Native"
"111","     Black or African American; Asian"
"112","     Black or African American; Native Hawaiian and Other Pacific Islander"
"113","     Black or African American; Some other race"
"114","     American Indian and Alaska Native; Asian"
"115","     American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander"
"116","     American Indian and Alaska Native; Some other race"
"117","     Asian; Native Hawaiian and Other Pacific Islander"
"118","     Asian; Some other race"
"119","     Native Hawaiian and Other Pacific Islander; Some other race"
"120","     White; Black or African American; American Indian and Alaska Native"
"121","     White; Black or African American; Asian"
"122","     White; Black or African American; Native Hawaiian and Other Pacific Islander"
"123","     White; Black or African American; Some other race"
"124","     White; American Indian and Alaska Native; Asian"
"125","     White; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander"
"126","     White; American Indian and Alaska Native; Some other race"
"127","     White; Asian; Native Hawaiian and Other Pacific Islander"
"128","     White; Asian; Some other race"
"129","     White; Native Hawaiian and Other Pacific Islander; Some other race"
"130","     Black or African American; American Indian and Alaska Native; Asian"
"131","     Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander"
"132","     Black or African American; American Indian and Alaska Native; Some other race"
"133","     Black or African American; Asian; Native Hawaiian and Other Pacific Islander"
"134","     Black or African American; Asian; Some other race"
"135","     Black or African American; Native Hawaiian and Other Pacific Islander; Some other race"
"136","     American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander"
"137","     American Indian and Alaska Native; Asian; Some other race"
"138","     American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some other race"
"139","     Asian; Native Hawaiian and Other Pacific Islander; Some other race"
"140","     White; Black or African American; American Indian and Alaska Native; Asian"
"141","     White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander"
"142","     White; Black or African American; American Indian and Alaska Native; Some other race"
"143","     White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander"
"144","     White; Black or African American; Asian; Some other race"
"145","     White; Black or African American; Native Hawaiian and Other Pacific Islander; Some other race"
"146","     White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander"
"147","     White; American Indian and Alaska Native; Asian; Some other race"
"148","     White; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some other race"
"149","     White; Asian; Native Hawaiian and Other Pacific Islander; Some other race"
"150","     Black or African American; American Indian or Alaska Native; Asian; Native Hawaiian and Other Pacific Islander"
"151","     Black or African American; American Indian and Alaska Native; Asian; Some other race"
"152","     Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some other race"
"153","     Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some other race"
"154","     American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some other race"
"155","     White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander"
"156","     White; Black or African American; American Indian and Alaska Native; Asian; Some other race"
"157","     White; Black or African American; American Indian and Alaska Native; Native Hawaiian and Other Pacific Islander; Some other race"
"158","     White; Black or African American; Asian; Native Hawaiian and Other Pacific Islander; Some other race"
"159","     White; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some other race"
"160","     Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some other race"
"161","     White; Black or African American; American Indian and Alaska Native; Asian; Native Hawaiian and Other Pacific Islander; Some other race"
"200","   Alaskan Athabascan alone"
"201","   Alaskan Athabascan alone or in any combination"
"202","   Aleut alone"
"203","   Aleut alone or in any combination"
"204","   Apache alone"
"205","   Apache alone or in any combination"
"206","   Blackfeet alone"
"207","   Blackfeet alone or in any combination"
"208","   Cherokee alone"
"209","   Cherokee alone or in any combination"
"210","   Cheyenne alone"
"211","   Cheyenne alone or in any combination"
"212","   Chickasaw alone"
"213","   Chickasaw alone or in any combination"
"214","   Chippewa alone"
"215","   Chippewa alone or in any combination"
"216","   Choctaw alone"
"217","   Choctaw alone or in any combination"
"218","   Colville alone"
"219","   Colville alone or in any combination"
"220","   Comanche alone"
"221","   Comanche alone or in any combination"
"222","   Cree alone"
"223","   Cree alone or in any combination"
"224","   Creek alone"
"225","   Creek alone or in any combination"
"226","   Crow alone"
"227","   Crow alone or in any combination"
"228","   Delaware alone"
"229","   Delaware alone or in any combination"
"230","   Eskimo alone"
"231","   Eskimo alone or in any combination"
"232","   Houma alone"
"233","   Houma alone or in any combination"
"234","   Iroquois alone"
"235","   Iroquois alone or in any combination"
"236","   Kiowa alone"
"237","   Kiowa alone or in any combination"
"238","   Latin American Indian alone"
"239","   Latin American Indian alone or in any combination"
"240","   Lumbee alone"
"241","   Lumbee alone or in any combination"
"242","   Menominee alone"
"243","   Menominee alone or in any combination"
"244","   Navajo alone"
"245","   Navajo alone or in any combination"
"246","   Osage alone"
"247","   Osage alone or in any combination"
"248","   Ottawa alone"
"249","   Ottawa alone or in any combination"
"250","   Paiute alone"
"251","   Paiute alone or in any combination"
"252","   Pima alone"
"253","   Pima alone or in any combination"
"254","   Potawatomi alone"
"255","   Potawatomi alone or in any combination"
"256","   Pueblo alone"
"257","   Pueblo alone or in any combination"
"258","   Puget Sound Salish alone"
"259","   Puget Sound Salish alone or in any combination"
"260","   Seminole alone"
"261","   Seminole alone or in any combination"
"262","   Shoshone alone"
"263","   Shoshone alone or in any combination"
"264","   Sioux alone"
"265","   Sioux alone or in any combination"
"266","   Tlingit-Haida alone"
"267","   Tlingit-Haida alone or in any combination"
"268","   Tohono O'Odham alone"
"269","   Tohono O'Odham alone or in any combination"
"270","   Ute alone"
"271","   Ute alone or in any combination"
"272","   Yakama alone"
"273","   Yakama alone or in any combination"
"274","   Yaqui alone"
"275","   Yaqui alone or in any combination"
"276","   Yuman alone"
"277","   Yuman alone or in any combination"
"400","   Hispanic or Latino (of any race)"
"401","     Mexican"
"402","     Puerto Rican"
"403","     Cuban"
"404","     Other Hispanic or Latino"
"405","        Dominican (Dominican Republic)"
"406","        Central American"
"407","          Costa Rican"
"408","          Guatemalan"
"409","          Honduran"
"410","          Nicaraguan"
"411","          Panamanian"
"412","          Salvadoran"
"413","        South American"
"414","          Argentinian"
"415","          Bolivian"
"416","          Chilean"
"417","          Colombian"
"418","          Ecuadorian"
"419","          Paraguayan"
"420","          Peruvian"
"421","          Uruguayan"
"422","          Venezuelan"
"423","        Spaniard"
"424","        All other Hispanic or Latino"
"450","   Not Hispanic or Latino"
"451","     White alone"
"452","     White alone or in combination with one or more other races"
"453","     Black or African American alone"
"454","     Black or African American alone or in combination with one or more other races"
"455","     American Indian and Alaska Native alone"
"456","     American Indian and Alaska Native alone or in combination with one or more other races"
"457","     Asian alone"
"458","     Asian alone or in combination with one or more other races"
"459","     Native Hawaiian and Other Pacific Islander alone"
"460","     Native Hawaiian and Other Pacific Islander alone or in combination with one or more other races"
"461","     Some other race alone"
"462","     Some other race alone or in combination with one or more other races"
"463","     Two or more races"
